---
server:
    install: '1'
    packages: [vim, git]
    timezone: UTC
    locale: en_US.UTF-8
    swap_size: 1024 # in MB
vagrant_local:
    install: '1'
    vm: { base_box: '', hostname: default, ip: 192.168.55.99, memory: '1024', sharedfolder: ./, syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/web
    servername: demo.dev
mysql:
    install: '1'
    root_password: '321321321'
    database: demo
    user: vagrant
    password: vagrant
    dump: ''
php:
    install: '1'
    ppa: php
    version: 5.6
    packages: [php5.6-cli, php5.6-intl, php5.6-mcrypt, php5.6-mysql, php5.6-curl, php5.6-dom, php5.6-zip, php5.6-mbstring, php5.6-xdebug]

composer:
    install: '1'

project_root: /vagrant